# Generated by Django 4.2.2 on 2023-10-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Lugar')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Dirección')),
                ('coordinates', models.CharField(max_length=255, unique=True, verbose_name='Coordenadas')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
    ]
