# Generated by Django 4.2.2 on 2023-08-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '¿Lugare?', 'verbose_name_plural': '¿Lugares?'},
        ),
    ]
