# Generated by Django 4.2.2 on 2023-08-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_address_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Coordenadas'),
        ),
    ]
