# Generated by Django 4.2.2 on 2023-08-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='google_maps_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
