# Generated by Django 4.2.2 on 2023-10-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_location_options_location_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='Cargar Direccion', max_length=255, unique=True, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=models.CharField(default=(0, 0), max_length=255, unique=True, verbose_name='Coordenadas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='Cargar', max_length=255, unique=True, verbose_name='Lugar'),
            preserve_default=False,
        ),
    ]
