# Generated by Django 4.2.2 on 2023-08-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('description_button', models.CharField(blank=True, max_length=255, null=True)),
                ('link_button', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(help_text='Este numero se utiliza para determinar el orden del carrousel. Menor numero, mayor prioridad.')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
