# Generated by Django 4.2.2 on 2023-08-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_carousel_image_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Carrusel', 'verbose_name_plural': 'Carruseles'},
        ),
    ]
