# Generated by Django 4.2.2 on 2023-08-29 15:58

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0003_alter_carousel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='description_button',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del botón'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to=event.models.image_upload_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.image_upload_path, verbose_name='Imagen mobile'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='link_button',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link del botón'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='order',
            field=models.IntegerField(help_text='Este numero se utiliza para determinar el orden del carrousel. Menor numero, mayor prioridad.', verbose_name='Orden'),
        ),
    ]
