# Generated by Django 4.2.2 on 2023-07-31 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('has_ticket', models.BooleanField(blank=True, null=True)),
                ('ticket_price', models.IntegerField(blank=True, null=True)),
                ('tickets_left', models.BooleanField(blank=True, null=True)),
                ('tickets_available', models.IntegerField(blank=True, null=True)),
                ('buy_tickets', models.CharField(blank=True, max_length=255, null=True)),
                ('event_link', models.CharField(blank=True, max_length=255, null=True)),
                ('event_img', models.ImageField(max_length=255, upload_to='images/')),
                ('organization_page', models.CharField(blank=True, max_length=255, null=True)),
                ('event_location', models.CharField(max_length=255)),
                ('highlighted', models.BooleanField(blank=True, default=False, null=True)),
                ('user_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
