# Generated by Django 4.2.1 on 2023-06-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('has_ticket', models.BooleanField(null=True)),
                ('ticket_price', models.IntegerField(null=True)),
                ('tickets_left', models.BooleanField(null=True)),
                ('tickets_available', models.IntegerField(null=True)),
                ('buy_tickets', models.CharField(max_length=255, null=True)),
                ('event_link', models.CharField(max_length=255, null=True)),
                ('event_img', models.CharField(max_length=255, null=True)),
                ('organization_page', models.CharField(max_length=255, null=True)),
                ('event_location', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
