# Generated by Django 4.2.2 on 2023-07-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
