# Generated by Django 4.2.2 on 2023-07-20 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_alter_event_event_type_alter_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
