# Generated by Django 4.2.2 on 2023-10-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='buy_tickets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link para comprar tickets:'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('virtual', 'Entrada virtual'), ('fisica', 'Entrada física'), ('fisica y virtual', 'Entrada fisica y virtual')], help_text='Entrada virtual, física, etc', max_length=255, null=True, verbose_name='Tipo de entrada'),
        ),
    ]
