# Generated by Django 4.2.2 on 2023-07-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_user_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='highlighted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
    ]
