# Generated by Django 4.2.2 on 2023-10-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_buy_tickets_alter_event_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('Entrada virtual', 'Entrada virtual'), ('Entrada física', 'Entrada fisica'), ('Entrada física y virtual', 'Entrada fisica y virtual')], help_text='Entrada virtual, física, etc', max_length=255, null=True, verbose_name='Tipo de entrada'),
        ),
    ]
