# Generated by Django 4.2.2 on 2023-08-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(blank=True, help_text='Entrada virtual, física, etc', max_length=255, null=True),
        ),
    ]
