# Generated by Django 4.2.2 on 2023-07-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_buy_tickets_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
