# Generated by Django 4.2.2 on 2023-12-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='date_to_repeat',
            field=models.ManyToManyField(to='event.dateevent'),
        ),
    ]
