# Generated by Django 4.2.2 on 2023-08-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_options'),
        ('event', '0006_event_description_event_ticket_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location', to_field='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=255, verbose_name='Nombre del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_ticket',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tiene ticket?'),
        ),
    ]
