# Generated by Django 4.2.2 on 2023-12-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_dateevent_event_date_to_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_to_repeat',
            field=models.ManyToManyField(blank=True, null=True, to='event.dateevent'),
        ),
    ]
