# Generated by Django 4.2.2 on 2023-08-11 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_name'),
        ('event', '0006_event_creator_showed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='buy_tickets',
            field=models.CharField(blank=True, help_text='Acá va un link a donde comprar las entradas.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Tipo de evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', to_field='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.CharField(blank=True, help_text='Acá links al evento (por ejemplo URLs de Instagram.)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(help_text='Dirección del evento.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization_page',
            field=models.CharField(blank=True, help_text='Acá link a redes de organizadores.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.IntegerField(blank=True, help_text='En pesos.', null=True),
        ),
    ]
