# Generated by Django 4.2.2 on 2023-08-23 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_address_alter_location_name'),
        ('category', '0003_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0007_alter_event_options_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='buy_tickets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comprar tickets:'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', to_field='name', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.ImageField(max_length=255, upload_to='images/', verbose_name='Imagen del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link al evento:'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(max_length=255, verbose_name='Dirección del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_ticket',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tiene entrada?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='highlighted',
            field=models.BooleanField(default=False, verbose_name='¿Evento destacado?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location', to_field='name', verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization_page',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Página organización'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name='Inicio del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(blank=True, help_text='Entrada virtual, física, etc', max_length=255, null=True, verbose_name='Tipo de entrada'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_available',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de entradas disponibles'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_left',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Quedan entradas?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Organización'),
        ),
    ]
