# Generated by Django 4.2.2 on 2023-08-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_event_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_location',
        ),
    ]
