# Generated by Django 4.2.2 on 2023-08-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_event_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='location_name',
        ),
    ]
