# Generated by Django 4.2.2 on 2023-09-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_location_options_location_coordinates'),
        ('event', '0011_rename_location_event_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_name',
        ),
        migrations.AddField(
            model_name='event',
            name='location_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location', verbose_name='Lugar'),
        ),
    ]
