# Generated by Django 4.2.2 on 2023-11-21 15:02

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to=event.models.image_upload_path, verbose_name='Imagen')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to=event.models.image_upload_path, verbose_name='Imagen mobile')),
                ('description_button', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del botón')),
                ('link_button', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link del botón')),
                ('order', models.IntegerField(help_text='Este numero se utiliza para determinar el orden del banner. Menor numero, mayor prioridad.', verbose_name='Orden')),
                ('active', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
